BEGIN;

DO $$
BEGIN
    IF (
        SELECT COUNT(*)
        FROM public.modulos_curso mc
        JOIN public.cursos c ON c.id = mc.curso_id
        WHERE mc.activo = TRUE
          AND (
            (c.codigo IN ('ESP-001', 'ESP-002', 'ESP-003', 'ESP-004', 'CORP-001', 'CORP-002') AND mc.numero BETWEEN 1 AND 4)
            OR (c.codigo IN ('ESP-005', 'ESP-006') AND mc.numero BETWEEN 1 AND 10)
            OR (c.codigo IN ('CORP-003', 'CORP-004', 'CORP-005') AND mc.numero BETWEEN 1 AND 3)
          )
    ) <> 53 THEN
        RAISE EXCEPTION 'Deben existir los 53 módulos activos antes de cargar sus contenidos.';
    END IF;
END $$;

INSERT INTO public.contenidos_curso (
    modulo_id, titulo, tipo, descripcion, orden, estado
)
SELECT
    mc.id, datos.titulo, datos.tipo, datos.descripcion, datos.orden, 'Publicado'
FROM (
    VALUES
    ('ESP-001', 1, 1, 'Estructura de una planilla y conceptos remunerativos y no remunerativos.', 'pdf', NULL::TEXT),
    ('ESP-001', 1, 2, 'Sueldo básico, asignación familiar, horas extras, comisiones, bonificaciones y otros conceptos.', 'pdf', NULL::TEXT),
    ('ESP-001', 1, 3, 'Descuentos del trabajador: criterios generales y aportes.', 'docx', NULL::TEXT),
    ('ESP-001', 1, 4, 'AFP y ONP: identificación y aplicación en casos prácticos.', 'docx', NULL::TEXT),
    ('ESP-001', 1, 5, 'Revisión y control de errores en planillas.', 'pdf', NULL::TEXT),
    ('ESP-001', 1, 6, 'Actividad práctica: Gestión de remuneraciones y estructura de planillas', 'actividad', 'Construcción de una planilla desde cero. Cálculo de descuentos y aportes. Revisión de una planilla con errores. Producto del módulo: Planilla básica de remuneraciones correctamente calculada.'),
    ('ESP-001', 2, 1, 'Remuneración computable y criterios para cada beneficio.', 'pptx', NULL::TEXT),
    ('ESP-001', 2, 2, 'Cálculo de CTS.', 'docx', NULL::TEXT),
    ('ESP-001', 2, 3, 'Cálculo de gratificaciones y bonificación extraordinaria.', 'pdf', NULL::TEXT),
    ('ESP-001', 2, 4, 'Vacaciones y vacaciones truncas.', 'docx', NULL::TEXT),
    ('ESP-001', 2, 5, 'Casos con diferentes fechas de ingreso, cese y remuneraciones variables.', 'pdf', NULL::TEXT),
    ('ESP-001', 2, 6, 'Actividad práctica: Cálculo de CTS, gratificaciones y vacaciones', 'actividad', 'Resolución de casos de CTS, gratificaciones y vacaciones. Comparación de resultados y detección de errores. Producto del módulo: Matriz de cálculo de beneficios sociales.'),
    ('ESP-001', 3, 1, 'Conceptos que intervienen en una liquidación.', 'pdf', NULL::TEXT),
    ('ESP-001', 3, 2, 'Remuneraciones pendientes.', 'pdf', NULL::TEXT),
    ('ESP-001', 3, 3, 'CTS trunca, gratificación trunca y vacaciones truncas.', 'pptx', NULL::TEXT),
    ('ESP-001', 3, 4, 'Descuentos y revisión de la liquidación.', 'docx', NULL::TEXT),
    ('ESP-001', 3, 5, 'Errores frecuentes y controles previos al cierre.', 'pptx', NULL::TEXT),
    ('ESP-001', 3, 6, 'Actividad práctica: Liquidación de beneficios sociales', 'actividad', 'Elaboración paso a paso de una liquidación. Resolución de casos de renuncia y término de contrato. Producto del módulo: Liquidación de beneficios sociales completa.'),
    ('ESP-001', 4, 1, 'Análisis de un caso empresarial integral.', 'pptx', NULL::TEXT),
    ('ESP-001', 4, 2, 'Integración de remuneraciones, descuentos, aportes y beneficios.', 'pdf', NULL::TEXT),
    ('ESP-001', 4, 3, 'Cálculo de liquidación y revisión final.', 'docx', NULL::TEXT),
    ('ESP-001', 4, 4, 'Sustentación de resultados y retroalimentación.', 'pdf', NULL::TEXT),
    ('ESP-001', 4, 5, 'Actividad práctica: Taller integrador de planillas y liquidaciones', 'actividad', 'Resolución individual o grupal de un caso integral. Evaluación final basada en un reto profesional. Producto del módulo: Expediente integral de planilla, beneficios y liquidación.'),
    ('ESP-002', 1, 1, 'Factura, boleta, nota de crédito y nota de débito.', 'pptx', NULL::TEXT),
    ('ESP-002', 1, 2, 'Datos y condiciones que debe contener un comprobante.', 'pptx', NULL::TEXT),
    ('ESP-002', 1, 3, 'Operaciones gravadas, exoneradas y no gravadas: criterios generales.', 'pptx', NULL::TEXT),
    ('ESP-002', 1, 4, 'Emisión, anulación y corrección de comprobantes.', 'pdf', NULL::TEXT),
    ('ESP-002', 1, 5, 'Errores frecuentes y buenas prácticas de control.', 'pdf', NULL::TEXT),
    ('ESP-002', 1, 6, 'Actividad práctica: Emisión y gestión de comprobantes electrónicos', 'actividad', 'Simulación de emisión de comprobantes a partir de operaciones comerciales. Análisis de casos con errores y correcciones. Producto del módulo: Matriz práctica para seleccionar y revisar comprobantes.'),
    ('ESP-002', 2, 1, 'Registro de compras y registro de ventas.', 'pdf', NULL::TEXT),
    ('ESP-002', 2, 2, 'Documentación sustentatoria.', 'pptx', NULL::TEXT),
    ('ESP-002', 2, 3, 'Gastos y criterios de sustento.', 'pptx', NULL::TEXT),
    ('ESP-002', 2, 4, 'Crédito fiscal y requisitos generales.', 'pdf', NULL::TEXT),
    ('ESP-002', 2, 5, 'Organización y control de la información contable.', 'pdf', NULL::TEXT),
    ('ESP-002', 2, 6, 'Actividad práctica: Registro de compras, ventas y gastos', 'actividad', 'Registro de operaciones de una empresa durante un periodo mensual. Revisión y conciliación básica de registros. Producto del módulo: Registro mensual simplificado de operaciones.'),
    ('ESP-002', 3, 1, 'Débito fiscal y crédito fiscal.', 'docx', NULL::TEXT),
    ('ESP-002', 3, 2, 'Determinación del IGV.', 'docx', NULL::TEXT),
    ('ESP-002', 3, 3, 'Principales obligaciones tributarias según régimen.', 'pdf', NULL::TEXT),
    ('ESP-002', 3, 4, 'Retenciones, percepciones y detracciones: conceptos y aplicación en casos.', 'pdf', NULL::TEXT),
    ('ESP-002', 3, 5, 'Declaraciones, cronogramas y controles básicos.', 'pptx', NULL::TEXT),
    ('ESP-002', 3, 6, 'Actividad práctica: IGV y obligaciones tributarias de la MYPE', 'actividad', 'Determinación del IGV de un periodo. Resolución de casos con diferentes operaciones. Producto del módulo: Determinación tributaria mensual simulada.'),
    ('ESP-002', 4, 1, 'Caso empresarial con operaciones de compras, ventas y gastos.', 'docx', NULL::TEXT),
    ('ESP-002', 4, 2, 'Emisión y revisión de comprobantes.', 'pptx', NULL::TEXT),
    ('ESP-002', 4, 3, 'Registro de operaciones.', 'pdf', NULL::TEXT),
    ('ESP-002', 4, 4, 'Determinación tributaria.', 'pdf', NULL::TEXT),
    ('ESP-002', 4, 5, 'Identificación de errores y recomendaciones de control.', 'pptx', NULL::TEXT),
    ('ESP-002', 4, 6, 'Actividad práctica: Taller integral de gestión contable de una MYPE', 'actividad', 'Resolución de un caso integral de una MYPE. Presentación y sustentación de resultados. Producto del módulo: Expediente contable mensual simplificado de una MYPE.'),
    ('ESP-003', 1, 1, 'Licencias y descansos vinculados a la gestión laboral.', 'docx', NULL::TEXT),
    ('ESP-003', 1, 2, 'Maternidad, paternidad e incapacidad temporal: criterios generales.', 'docx', NULL::TEXT),
    ('ESP-003', 1, 3, 'Documentación y validación de información.', 'docx', NULL::TEXT),
    ('ESP-003', 1, 4, 'Responsabilidades del trabajador y del empleador.', 'docx', NULL::TEXT),
    ('ESP-003', 1, 5, 'Control de fechas, incidencias y seguimiento.', 'pdf', NULL::TEXT),
    ('ESP-003', 1, 6, 'Actividad práctica: Gestión de licencias, descansos médicos y ausencias', 'actividad', 'Análisis de casos y determinación de la gestión que corresponde. Elaboración de una matriz de control y seguimiento. Producto del módulo: Matriz de gestión y seguimiento de licencias.'),
    ('ESP-003', 2, 1, 'Concepto y finalidad del subsidio.', 'docx', NULL::TEXT),
    ('ESP-003', 2, 2, 'Periodos a cargo del empleador y periodos subsidiados, según corresponda.', 'pptx', NULL::TEXT),
    ('ESP-003', 2, 3, 'Información remunerativa utilizada para el cálculo.', 'pptx', NULL::TEXT),
    ('ESP-003', 2, 4, 'Metodología de cálculo y variables que deben considerarse.', 'pdf', NULL::TEXT),
    ('ESP-003', 2, 5, 'Casos con diferentes periodos y situaciones.', 'docx', NULL::TEXT),
    ('ESP-003', 2, 6, 'Actividad práctica: Cálculo de subsidios por incapacidad temporal', 'actividad', 'Cálculo paso a paso de subsidios. Revisión de resultados y detección de inconsistencias. Producto del módulo: Hoja de cálculo de subsidio aplicada a un caso.'),
    ('ESP-003', 3, 1, 'Ruta administrativa para la gestión del subsidio.', 'docx', NULL::TEXT),
    ('ESP-003', 3, 2, 'Requisitos y documentación de respaldo.', 'pptx', NULL::TEXT),
    ('ESP-003', 3, 3, 'Armado y revisión del expediente.', 'docx', NULL::TEXT),
    ('ESP-003', 3, 4, 'Presentación, seguimiento y control.', 'pptx', NULL::TEXT),
    ('ESP-003', 3, 5, 'Observaciones, subsanaciones y cierre.', 'pptx', NULL::TEXT),
    ('ESP-003', 3, 6, 'Buenas prácticas para el seguimiento interno.', 'docx', NULL::TEXT),
    ('ESP-003', 3, 7, 'Actividad práctica: Gestión y recuperación de subsidios', 'actividad', 'Armado de un expediente de subsidio. Simulación de revisión documental y levantamiento de observaciones. Producto del módulo: Expediente práctico de gestión y recuperación de subsidio.'),
    ('ESP-003', 4, 1, 'Caso integral de incapacidad temporal o maternidad.', 'pptx', NULL::TEXT),
    ('ESP-003', 4, 2, 'Identificación del derecho y revisión documental.', 'pdf', NULL::TEXT),
    ('ESP-003', 4, 3, 'Cálculo del subsidio.', 'docx', NULL::TEXT),
    ('ESP-003', 4, 4, 'Ruta de gestión y seguimiento.', 'docx', NULL::TEXT),
    ('ESP-003', 4, 5, 'Resolución de inconsistencias y sustentación.', 'pdf', NULL::TEXT),
    ('ESP-003', 4, 6, 'Actividad práctica: Taller integral de subsidios y licencias', 'actividad', 'Resolución de casos con documentación incompleta y observaciones. Evaluación final mediante reto profesional. Producto del módulo: Caso integral: cálculo + expediente + ruta de gestión.'),
    ('ESP-004', 1, 1, 'Levantamiento de perfil y análisis de la necesidad.', 'pptx', NULL::TEXT),
    ('ESP-004', 1, 2, 'Funciones, requisitos y criterios excluyentes/deseables.', 'pdf', NULL::TEXT),
    ('ESP-004', 1, 3, 'Competencias y evidencias esperadas.', 'pptx', NULL::TEXT),
    ('ESP-004', 1, 4, 'Perfil ideal y estrategia de búsqueda.', 'pdf', NULL::TEXT),
    ('ESP-004', 1, 5, 'Fuentes y canales de atracción.', 'pptx', NULL::TEXT),
    ('ESP-004', 1, 6, 'Actividad práctica: Perfilamiento y estrategia de atracción de talento', 'actividad', 'Construcción de un perfil de puesto. Definición de competencias y criterios de evaluación. Diseño de una estrategia de atracción. Producto del módulo: Perfil de puesto + matriz de competencias.'),
    ('ESP-004', 2, 1, 'Qué es un ATS y cómo se utiliza en selección.', 'pdf', NULL::TEXT),
    ('ESP-004', 2, 2, 'Filtros, keywords, matching y ranking.', 'docx', NULL::TEXT),
    ('ESP-004', 2, 3, 'Screening curricular y trazabilidad.', 'pdf', NULL::TEXT),
    ('ESP-004', 2, 4, 'Longlist y shortlist.', 'pptx', NULL::TEXT),
    ('ESP-004', 2, 5, 'Limitaciones, sesgos y revisión humana.', 'docx', NULL::TEXT),
    ('ESP-004', 2, 6, 'Uso de IA para apoyar la búsqueda y clasificación.', 'pptx', NULL::TEXT),
    ('ESP-004', 2, 7, 'Actividad práctica: ATS, sourcing y screening de candidatos', 'actividad', 'Simulación de screening de candidatos. Construcción de shortlist a partir de una vacante. Identificación de candidatos que requieren revisión adicional. Producto del módulo: Shortlist sustentada + criterios de screening.'),
    ('ESP-004', 3, 1, 'Entrevista estructurada y semiestructurada.', 'docx', NULL::TEXT),
    ('ESP-004', 3, 2, 'Preguntas conductuales y método STAR.', 'pdf', NULL::TEXT),
    ('ESP-004', 3, 3, 'Evidencias de competencia.', 'pptx', NULL::TEXT),
    ('ESP-004', 3, 4, 'Escalas y matrices de evaluación.', 'pdf', NULL::TEXT),
    ('ESP-004', 3, 5, 'Sesgos del entrevistador.', 'docx', NULL::TEXT),
    ('ESP-004', 3, 6, 'IA como apoyo para preparar y ordenar información.', 'docx', NULL::TEXT),
    ('ESP-004', 3, 7, 'Actividad práctica: Entrevista y evaluación por competencias', 'actividad', 'Diseño de guía de entrevista. Role play de entrevista. Evaluación de respuestas y construcción de evidencias. Producto del módulo: Guía de entrevista + matriz de evaluación.'),
    ('ESP-004', 4, 1, 'Assessment Center y pruebas situacionales.', 'pptx', NULL::TEXT),
    ('ESP-004', 4, 2, 'Integración de resultados.', 'pptx', NULL::TEXT),
    ('ESP-004', 4, 3, 'Comparación objetiva de candidatos.', 'pptx', NULL::TEXT),
    ('ESP-004', 4, 4, 'Matriz de decisión.', 'docx', NULL::TEXT),
    ('ESP-004', 4, 5, 'Informe de evaluación y recomendación.', 'docx', NULL::TEXT),
    ('ESP-004', 4, 6, 'Experiencia del candidato y comunicación de resultados.', 'docx', NULL::TEXT),
    ('ESP-004', 4, 7, 'Actividad práctica: Assessment y decisión de selección', 'actividad', 'Caso integral: vacante → ATS → screening → entrevista → evaluación → recomendación. Sustentación de la decisión de selección. Producto del módulo: Informe final de evaluación y recomendación de candidato.'),
    ('ESP-005', 1, 1, 'Interfaz, libros, hojas, filas, columnas y rangos.', 'pdf', NULL::TEXT),
    ('ESP-005', 1, 2, 'Ingreso, edición y organización de datos.', 'pptx', NULL::TEXT),
    ('ESP-005', 1, 3, 'Formatos de número, fecha, texto y tablas.', 'pptx', NULL::TEXT),
    ('ESP-005', 1, 4, 'Ordenar, filtrar y buscar información.', 'docx', NULL::TEXT),
    ('ESP-005', 1, 5, 'Buenas prácticas para construir archivos ordenados.', 'pdf', NULL::TEXT),
    ('ESP-005', 1, 6, 'Actividad práctica: Fundamentos de Excel: domina la herramienta desde cero', 'actividad', 'Crear y organizar una base de datos desde cero. Aplicar formatos y filtros a una base de información. Corregir errores frecuentes de estructura y formato. Producto del módulo: Base de datos organizada y funcional.'),
    ('ESP-005', 2, 1, 'Referencias relativas, absolutas y mixtas.', 'pdf', NULL::TEXT),
    ('ESP-005', 2, 2, 'Operadores y fórmulas básicas.', 'pptx', NULL::TEXT),
    ('ESP-005', 2, 3, 'SUMA, PROMEDIO, MIN, MAX y CONTAR.', 'pdf', NULL::TEXT),
    ('ESP-005', 2, 4, 'Funciones de texto y fecha de uso frecuente.', 'pdf', NULL::TEXT),
    ('ESP-005', 2, 5, 'Copiar, replicar y auditar fórmulas.', 'docx', NULL::TEXT),
    ('ESP-005', 2, 6, 'Actividad práctica: Fórmulas esenciales para trabajar con datos', 'actividad', 'Construir cálculos de una operación empresarial. Aplicar referencias absolutas y mixtas. Resolver ejercicios de control y validación. Producto del módulo: Plantilla de cálculo con fórmulas esenciales.'),
    ('ESP-005', 3, 1, 'Tablas y estructuración de información.', 'pdf', NULL::TEXT),
    ('ESP-005', 3, 2, 'Filtros avanzados y criterios de búsqueda.', 'docx', NULL::TEXT),
    ('ESP-005', 3, 3, 'Formato condicional.', 'docx', NULL::TEXT),
    ('ESP-005', 3, 4, 'Validación de datos y listas desplegables.', 'docx', NULL::TEXT),
    ('ESP-005', 3, 5, 'Protección y control básico de archivos.', 'docx', NULL::TEXT),
    ('ESP-005', 3, 6, 'Actividad práctica: Excel para gestión y control', 'actividad', 'Diseñar una plantilla de control. Crear listas y reglas de validación. Detectar datos inconsistentes. Producto del módulo: Dashboard/plantilla de control operativo básica.'),
    ('ESP-005', 4, 1, 'SI y funciones condicionales.', 'pdf', NULL::TEXT),
    ('ESP-005', 4, 2, 'CONTAR.SI y SUMAR.SI.', 'pdf', NULL::TEXT),
    ('ESP-005', 4, 3, 'Funciones de búsqueda básicas.', 'pptx', NULL::TEXT),
    ('ESP-005', 4, 4, 'Combinación de funciones.', 'pptx', NULL::TEXT),
    ('ESP-005', 4, 5, 'Resolución de problemas cotidianos con fórmulas.', 'pdf', NULL::TEXT),
    ('ESP-005', 4, 6, 'Actividad práctica: Funciones que te hacen trabajar más rápido', 'actividad', 'Resolver casos de ventas, RR. HH. y administración. Construir indicadores automáticos. Optimizar una plantilla manual. Producto del módulo: Modelo automatizado de control.'),
    ('ESP-005', 5, 1, 'Concepto y construcción de tablas dinámicas.', 'docx', NULL::TEXT),
    ('ESP-005', 5, 2, 'Agrupación y filtros.', 'docx', NULL::TEXT),
    ('ESP-005', 5, 3, 'Segmentación de datos.', 'docx', NULL::TEXT),
    ('ESP-005', 5, 4, 'Indicadores y resúmenes.', 'pptx', NULL::TEXT),
    ('ESP-005', 5, 5, 'Interpretación de resultados.', 'pptx', NULL::TEXT),
    ('ESP-005', 5, 6, 'Actividad práctica: Tablas dinámicas y análisis básico', 'actividad', 'Analizar una base de ventas/recursos humanos. Crear reportes dinámicos. Responder preguntas de negocio con datos. Producto del módulo: Reporte dinámico de gestión.'),
    ('ESP-005', 6, 1, 'Selección del gráfico adecuado.', 'docx', NULL::TEXT),
    ('ESP-005', 6, 2, 'Gráficos de columnas, líneas, barras y circular.', 'docx', NULL::TEXT),
    ('ESP-005', 6, 3, 'Elementos visuales y lectura de datos.', 'docx', NULL::TEXT),
    ('ESP-005', 6, 4, 'Mini dashboard.', 'pptx', NULL::TEXT),
    ('ESP-005', 6, 5, 'Presentación de información para toma de decisiones.', 'pptx', NULL::TEXT),
    ('ESP-005', 6, 6, 'Actividad práctica: Gráficos e informes ejecutivos', 'actividad', 'Transformar datos en gráficos. Diseñar un reporte de una página. Presentar hallazgos principales. Producto del módulo: Reporte visual ejecutivo.'),
    ('ESP-005', 7, 1, 'Control de personal y asistencia.', 'docx', NULL::TEXT),
    ('ESP-005', 7, 2, 'Seguimiento de indicadores.', 'pdf', NULL::TEXT),
    ('ESP-005', 7, 3, 'Control de vacaciones, capacitaciones o incidencias.', 'pptx', NULL::TEXT),
    ('ESP-005', 7, 4, 'Matrices de seguimiento.', 'pdf', NULL::TEXT),
    ('ESP-005', 7, 5, 'Automatización básica de reportes.', 'pdf', NULL::TEXT),
    ('ESP-005', 7, 6, 'Actividad práctica: Excel aplicado a Recursos Humanos y Administración', 'actividad', 'Construir una matriz de RR. HH. Crear indicadores y alertas básicas. Generar un reporte de seguimiento. Producto del módulo: Matriz de gestión de RR. HH./Administración.'),
    ('ESP-005', 8, 1, 'Bases de clientes y oportunidades.', 'pptx', NULL::TEXT),
    ('ESP-005', 8, 2, 'Seguimiento de ventas.', 'pdf', NULL::TEXT),
    ('ESP-005', 8, 3, 'Metas, avances y cumplimiento.', 'pptx', NULL::TEXT),
    ('ESP-005', 8, 4, 'Comisiones y cálculos comerciales.', 'pdf', NULL::TEXT),
    ('ESP-005', 8, 5, 'Indicadores básicos de gestión.', 'docx', NULL::TEXT),
    ('ESP-005', 8, 6, 'Actividad práctica: Excel aplicado a ventas y gestión comercial', 'actividad', 'Crear un control comercial. Calcular cumplimiento de metas. Generar un reporte de resultados. Producto del módulo: Tablero comercial básico.'),
    ('ESP-005', 9, 1, 'Estructuración de una base realista.', 'docx', NULL::TEXT),
    ('ESP-005', 9, 2, 'Limpieza y validación de datos.', 'pptx', NULL::TEXT),
    ('ESP-005', 9, 3, 'Aplicación de fórmulas y funciones.', 'pdf', NULL::TEXT),
    ('ESP-005', 9, 4, 'Tablas dinámicas y gráficos.', 'pdf', NULL::TEXT),
    ('ESP-005', 9, 5, 'Construcción del reporte final.', 'pptx', NULL::TEXT),
    ('ESP-005', 9, 6, 'Actividad práctica: Proyecto integrador: de la base de datos al reporte', 'actividad', 'Resolver un caso integral paso a paso. Integrar herramientas aprendidas. Presentar el archivo y sustentar resultados. Producto del módulo: Archivo integral de gestión en Excel.'),
    ('ESP-005', 10, 1, 'Análisis de un caso empresarial.', 'pdf', NULL::TEXT),
    ('ESP-005', 10, 2, 'Selección de herramientas según el problema.', 'docx', NULL::TEXT),
    ('ESP-005', 10, 3, 'Construcción de solución en Excel.', 'pdf', NULL::TEXT),
    ('ESP-005', 10, 4, 'Revisión, mejora y presentación.', 'docx', NULL::TEXT),
    ('ESP-005', 10, 5, 'Buenas prácticas para entregar archivos profesionales.', 'pdf', NULL::TEXT),
    ('ESP-005', 10, 6, 'Actividad práctica: Reto final: Excel para resolver problemas reales', 'actividad', 'Resolver un reto individual o grupal. Defender la lógica utilizada. Recibir retroalimentación y optimizar el archivo. Producto del módulo: Proyecto final de Excel listo para uso laboral.'),
    ('ESP-006', 1, 1, 'Funciones condicionales avanzadas.', 'pptx', NULL::TEXT),
    ('ESP-006', 1, 2, 'Funciones de búsqueda y referencia.', 'pptx', NULL::TEXT),
    ('ESP-006', 1, 3, 'Combinación de funciones.', 'docx', NULL::TEXT),
    ('ESP-006', 1, 4, 'Funciones de texto, fecha y lógica.', 'pptx', NULL::TEXT),
    ('ESP-006', 1, 5, 'Diseño de fórmulas robustas.', 'pptx', NULL::TEXT),
    ('ESP-006', 1, 6, 'Actividad práctica: Excel Profesional: fórmulas y funciones avanzadas', 'actividad', 'Resolver casos complejos de negocio. Construir fórmulas combinadas. Optimizar modelos existentes. Producto del módulo: Modelo avanzado de cálculo.'),
    ('ESP-006', 2, 1, 'Estructuración y limpieza de bases.', 'pptx', NULL::TEXT),
    ('ESP-006', 2, 2, 'Criterios de calidad de datos.', 'pdf', NULL::TEXT),
    ('ESP-006', 2, 3, 'Análisis exploratorio.', 'pdf', NULL::TEXT),
    ('ESP-006', 2, 4, 'Indicadores y métricas.', 'pptx', NULL::TEXT),
    ('ESP-006', 2, 5, 'Lectura e interpretación para decisiones.', 'pptx', NULL::TEXT),
    ('ESP-006', 2, 6, 'Actividad práctica: Excel para análisis de datos y toma de decisiones', 'actividad', 'Limpiar una base realista. Construir indicadores. Extraer conclusiones accionables. Producto del módulo: Base depurada + matriz de indicadores.'),
    ('ESP-006', 3, 1, 'Modelos de tablas dinámicas.', 'docx', NULL::TEXT),
    ('ESP-006', 3, 2, 'Segmentadores y líneas de tiempo.', 'docx', NULL::TEXT),
    ('ESP-006', 3, 3, 'Campos calculados y agrupaciones.', 'pptx', NULL::TEXT),
    ('ESP-006', 3, 4, 'Diseño de dashboards.', 'docx', NULL::TEXT),
    ('ESP-006', 3, 5, 'Interactividad y lectura ejecutiva.', 'pdf', NULL::TEXT),
    ('ESP-006', 3, 6, 'Actividad práctica: Tablas dinámicas avanzadas y dashboards', 'actividad', 'Construir un dashboard desde una base. Diseñar filtros interactivos. Presentar indicadores clave. Producto del módulo: Dashboard ejecutivo interactivo.'),
    ('ESP-006', 4, 1, 'Introducción a Power Query.', 'docx', NULL::TEXT),
    ('ESP-006', 4, 2, 'Importación y conexión de fuentes.', 'pdf', NULL::TEXT),
    ('ESP-006', 4, 3, 'Limpieza y transformación.', 'docx', NULL::TEXT),
    ('ESP-006', 4, 4, 'Combinar y anexar consultas.', 'pdf', NULL::TEXT),
    ('ESP-006', 4, 5, 'Actualización de información.', 'pdf', NULL::TEXT),
    ('ESP-006', 4, 6, 'Actividad práctica: Power Query: transforma y automatiza tus datos', 'actividad', 'Importar y transformar una base. Combinar archivos. Crear un flujo actualizable. Producto del módulo: Consulta automatizada para transformación de datos.'),
    ('ESP-006', 5, 1, 'Modelo de datos.', 'pdf', NULL::TEXT),
    ('ESP-006', 5, 2, 'Relaciones entre tablas.', 'pptx', NULL::TEXT),
    ('ESP-006', 5, 3, 'Tablas calendario y dimensiones.', 'pptx', NULL::TEXT),
    ('ESP-006', 5, 4, 'Medidas y cálculos.', 'docx', NULL::TEXT),
    ('ESP-006', 5, 5, 'Introducción a DAX aplicado.', 'pptx', NULL::TEXT),
    ('ESP-006', 5, 6, 'Actividad práctica: Modelamiento de datos y Power Pivot', 'actividad', 'Relacionar varias tablas. Construir medidas. Analizar información desde un modelo. Producto del módulo: Modelo de datos funcional.'),
    ('ESP-006', 6, 1, 'Conceptos de automatización.', 'docx', NULL::TEXT),
    ('ESP-006', 6, 2, 'Grabación y edición básica de macros.', 'pdf', NULL::TEXT),
    ('ESP-006', 6, 3, 'Variables, procedimientos y eventos básicos.', 'pdf', NULL::TEXT),
    ('ESP-006', 6, 4, 'Botones y automatización de tareas repetitivas.', 'pptx', NULL::TEXT),
    ('ESP-006', 6, 5, 'Buenas prácticas y seguridad.', 'pptx', NULL::TEXT),
    ('ESP-006', 6, 6, 'Actividad práctica: Automatización de tareas con macros y VBA', 'actividad', 'Automatizar una tarea repetitiva. Crear un botón de ejecución. Mejorar un archivo mediante macros. Producto del módulo: Macro funcional para un proceso real.'),
    ('ESP-006', 7, 1, 'Presupuestos y variaciones.', 'pptx', NULL::TEXT),
    ('ESP-006', 7, 2, 'Flujo de caja básico.', 'pptx', NULL::TEXT),
    ('ESP-006', 7, 3, 'Proyecciones y escenarios.', 'pptx', NULL::TEXT),
    ('ESP-006', 7, 4, 'Indicadores financieros.', 'pdf', NULL::TEXT),
    ('ESP-006', 7, 5, 'Modelos para control de gestión.', 'pdf', NULL::TEXT),
    ('ESP-006', 7, 6, 'Actividad práctica: Excel para finanzas y control de gestión', 'actividad', 'Construir un modelo presupuestal. Analizar desviaciones. Simular escenarios. Producto del módulo: Modelo financiero de gestión.'),
    ('ESP-006', 8, 1, 'Bases de colaboradores.', 'pptx', NULL::TEXT),
    ('ESP-006', 8, 2, 'Indicadores de rotación, ausentismo y dotación.', 'pdf', NULL::TEXT),
    ('ESP-006', 8, 3, 'Segmentación y análisis.', 'docx', NULL::TEXT),
    ('ESP-006', 8, 4, 'Dashboards de RR. HH.', 'pptx', NULL::TEXT),
    ('ESP-006', 8, 5, 'Interpretación de indicadores.', 'pptx', NULL::TEXT),
    ('ESP-006', 8, 6, 'Actividad práctica: Excel para RR. HH. y People Analytics', 'actividad', 'Construir una base de People Analytics. Calcular indicadores. Diseñar un dashboard de RR. HH. Producto del módulo: Dashboard de People Analytics.'),
    ('ESP-006', 9, 1, 'Auditoría de fórmulas.', 'docx', NULL::TEXT),
    ('ESP-006', 9, 2, 'Errores y trazabilidad.', 'docx', NULL::TEXT),
    ('ESP-006', 9, 3, 'Optimización de archivos pesados.', 'pdf', NULL::TEXT),
    ('ESP-006', 9, 4, 'Estructuras escalables.', 'pptx', NULL::TEXT),
    ('ESP-006', 9, 5, 'Buenas prácticas de modelamiento.', 'pptx', NULL::TEXT),
    ('ESP-006', 9, 6, 'Actividad práctica: Optimización de modelos y resolución de problemas', 'actividad', 'Auditar un modelo con errores. Reducir pasos manuales. Optimizar estructura y fórmulas. Producto del módulo: Modelo optimizado y documentado.'),
    ('ESP-006', 10, 1, 'Definición del problema empresarial.', 'pptx', NULL::TEXT),
    ('ESP-006', 10, 2, 'Selección de fuentes y estructura.', 'pptx', NULL::TEXT),
    ('ESP-006', 10, 3, 'Transformación y modelamiento.', 'pdf', NULL::TEXT),
    ('ESP-006', 10, 4, 'Análisis, dashboard y automatización.', 'pdf', NULL::TEXT),
    ('ESP-006', 10, 5, 'Presentación ejecutiva de resultados.', 'pptx', NULL::TEXT),
    ('ESP-006', 10, 6, 'Actividad práctica: Proyecto integrador: Excel Professional Challenge', 'actividad', 'Resolver un caso integral. Construir una solución de principio a fin. Sustentar decisiones técnicas y resultados. Producto del módulo: Proyecto profesional integral en Excel.'),
    ('CORP-001', 1, 1, 'Fortalezas individuales y colectivas.', 'docx', NULL::TEXT),
    ('CORP-001', 1, 2, 'Roles y estilos dentro del equipo.', 'docx', NULL::TEXT),
    ('CORP-001', 1, 3, 'Diversidad y complementariedad.', 'pdf', NULL::TEXT),
    ('CORP-001', 1, 4, 'Confianza y seguridad psicológica.', 'pptx', NULL::TEXT),
    ('CORP-001', 1, 5, 'Factores que favorecen la colaboración.', 'docx', NULL::TEXT),
    ('CORP-001', 1, 6, 'Actividad práctica: Conociendo nuestro equipo', 'actividad', 'Dinámica de integración y autodiagnóstico del equipo. Reto para identificar fortalezas y oportunidades. Producto del módulo: Mapa de fortalezas y oportunidades del equipo.'),
    ('CORP-001', 2, 1, 'Escucha activa.', 'pdf', NULL::TEXT),
    ('CORP-001', 2, 2, 'Comunicación clara y asertiva.', 'pptx', NULL::TEXT),
    ('CORP-001', 2, 3, 'Barreras de comunicación.', 'docx', NULL::TEXT),
    ('CORP-001', 2, 4, 'Feedback entre compañeros.', 'docx', NULL::TEXT),
    ('CORP-001', 2, 5, 'Interpretación y coordinación de mensajes.', 'pdf', NULL::TEXT),
    ('CORP-001', 2, 6, 'Actividad práctica: Comunicación que conecta', 'actividad', 'Dinámica de comunicación bajo restricciones. Ejercicio de escucha y feedback. Producto del módulo: Acuerdos de comunicación efectiva.'),
    ('CORP-001', 3, 1, 'Resolución colaborativa de problemas.', 'docx', NULL::TEXT),
    ('CORP-001', 3, 2, 'Coordinación y toma de decisiones.', 'pptx', NULL::TEXT),
    ('CORP-001', 3, 3, 'Roles ante situaciones de presión.', 'pdf', NULL::TEXT),
    ('CORP-001', 3, 4, 'Confianza y corresponsabilidad.', 'pdf', NULL::TEXT),
    ('CORP-001', 3, 5, 'Actividad práctica: Retos colaborativos', 'actividad', 'Reto colaborativo con roles asignados. Debrief y análisis de comportamientos observados. Producto del módulo: Matriz de aprendizajes del reto.'),
    ('CORP-001', 4, 1, 'Comportamientos deseados.', 'pdf', NULL::TEXT),
    ('CORP-001', 4, 2, 'Acuerdos de convivencia y colaboración.', 'pdf', NULL::TEXT),
    ('CORP-001', 4, 3, 'Compromisos individuales y colectivos.', 'pptx', NULL::TEXT),
    ('CORP-001', 4, 4, 'Seguimiento de acuerdos.', 'pdf', NULL::TEXT),
    ('CORP-001', 4, 5, 'Actividad práctica: Nuestro acuerdo de equipo', 'actividad', 'Construcción del Team Agreement. Definición de 3 compromisos accionables por equipo. Producto del módulo: Team Agreement con compromisos de trabajo.'),
    ('CORP-002', 1, 1, 'Liderazgo vs. autoridad.', 'pdf', NULL::TEXT),
    ('CORP-002', 1, 2, 'Estilos de liderazgo.', 'pptx', NULL::TEXT),
    ('CORP-002', 1, 3, 'Autodiagnóstico del estilo personal.', 'pptx', NULL::TEXT),
    ('CORP-002', 1, 4, 'Liderazgo situacional.', 'pdf', NULL::TEXT),
    ('CORP-002', 1, 5, 'Rol del líder en el desempeño.', 'docx', NULL::TEXT),
    ('CORP-002', 1, 6, 'Actividad práctica: El líder como movilizador', 'actividad', 'Caso de liderazgo y toma de decisiones. Autodiagnóstico y plan de mejora. Producto del módulo: Perfil de fortalezas y oportunidades del líder.'),
    ('CORP-002', 2, 1, 'Comunicación del líder.', 'docx', NULL::TEXT),
    ('CORP-002', 2, 2, 'Escucha activa.', 'docx', NULL::TEXT),
    ('CORP-002', 2, 3, 'Feedback positivo y correctivo.', 'pdf', NULL::TEXT),
    ('CORP-002', 2, 4, 'Expectativas y acuerdos.', 'pdf', NULL::TEXT),
    ('CORP-002', 2, 5, 'Conversaciones de desempeño.', 'docx', NULL::TEXT),
    ('CORP-002', 2, 6, 'Actividad práctica: Comunicación y feedback', 'actividad', 'Role play de feedback. Retroalimentación entre participantes. Producto del módulo: Guía de conversación de feedback.'),
    ('CORP-002', 3, 1, 'Qué delegar y qué no.', 'pdf', NULL::TEXT),
    ('CORP-002', 3, 2, 'Asignación clara de responsabilidades.', 'pdf', NULL::TEXT),
    ('CORP-002', 3, 3, 'Seguimiento sin micromanagement.', 'docx', NULL::TEXT),
    ('CORP-002', 3, 4, 'Accountability.', 'pptx', NULL::TEXT),
    ('CORP-002', 3, 5, 'Indicadores y compromisos.', 'docx', NULL::TEXT),
    ('CORP-002', 3, 6, 'Actividad práctica: Delegación y gestión del desempeño', 'actividad', 'Caso de delegación. Diseño de una conversación de asignación de tarea. Producto del módulo: Matriz de delegación y seguimiento.'),
    ('CORP-002', 4, 1, 'Bajo desempeño.', 'pptx', NULL::TEXT),
    ('CORP-002', 4, 2, 'Conflictos interpersonales.', 'docx', NULL::TEXT),
    ('CORP-002', 4, 3, 'Resistencia y desacuerdos.', 'pdf', NULL::TEXT),
    ('CORP-002', 4, 4, 'Preparación de conversaciones difíciles.', 'pptx', NULL::TEXT),
    ('CORP-002', 4, 5, 'Cierre y acuerdos.', 'pptx', NULL::TEXT),
    ('CORP-002', 4, 6, 'Actividad práctica: Conversaciones difíciles', 'actividad', 'Simulación de conversación con colaborador. Role play con retroalimentación. Producto del módulo: Plan de acción de liderazgo de 30 días.'),
    ('CORP-003', 1, 1, 'Conceptos fundamentales de SST.', 'docx', NULL::TEXT),
    ('CORP-003', 1, 2, 'Cultura de prevención.', 'docx', NULL::TEXT),
    ('CORP-003', 1, 3, 'Responsabilidades de empleador y trabajadores.', 'pdf', NULL::TEXT),
    ('CORP-003', 1, 4, 'Rol de líderes y supervisores.', 'docx', NULL::TEXT),
    ('CORP-003', 1, 5, 'Comportamientos seguros y prevención.', 'docx', NULL::TEXT),
    ('CORP-003', 1, 6, 'Actividad práctica: Cultura preventiva y responsabilidades', 'actividad', 'Análisis de casos de cultura preventiva. Identificación de conductas seguras e inseguras. Producto del módulo: Mapa de comportamientos preventivos.'),
    ('CORP-003', 2, 1, 'Peligro vs. riesgo.', 'docx', NULL::TEXT),
    ('CORP-003', 2, 2, 'Identificación de peligros.', 'docx', NULL::TEXT),
    ('CORP-003', 2, 3, 'Evaluación de riesgos.', 'pptx', NULL::TEXT),
    ('CORP-003', 2, 4, 'Medidas de control.', 'pptx', NULL::TEXT),
    ('CORP-003', 2, 5, 'Jerarquía de controles.', 'pptx', NULL::TEXT),
    ('CORP-003', 2, 6, 'Errores frecuentes.', 'pdf', NULL::TEXT),
    ('CORP-003', 2, 7, 'Actividad práctica: Identificación de peligros y evaluación de riesgos', 'actividad', 'Construcción de una matriz de riesgos sobre un caso. Priorización de riesgos y controles. Producto del módulo: Matriz práctica de identificación y control de riesgos.'),
    ('CORP-003', 3, 1, 'Actos y condiciones inseguras.', 'pdf', NULL::TEXT),
    ('CORP-003', 3, 2, 'Reporte de incidentes.', 'pptx', NULL::TEXT),
    ('CORP-003', 3, 3, 'Investigación básica de incidentes.', 'pdf', NULL::TEXT),
    ('CORP-003', 3, 4, 'Comunicación preventiva.', 'pptx', NULL::TEXT),
    ('CORP-003', 3, 5, 'Acciones correctivas y preventivas.', 'pdf', NULL::TEXT),
    ('CORP-003', 3, 6, 'Seguimiento.', 'docx', NULL::TEXT),
    ('CORP-003', 3, 7, 'Actividad práctica: Prevención aplicada al trabajo', 'actividad', 'Análisis de un incidente simulado. Diseño de acciones preventivas y plan de seguimiento. Producto del módulo: Plan de acciones preventivas.'),
    ('CORP-004', 1, 1, 'IA generativa y principales usos laborales.', 'pdf', NULL::TEXT),
    ('CORP-004', 1, 2, 'Qué puede y qué no puede hacer la IA.', 'pptx', NULL::TEXT),
    ('CORP-004', 1, 3, 'Estructura de un buen prompt.', 'pdf', NULL::TEXT),
    ('CORP-004', 1, 4, 'Contexto, rol, objetivo, restricciones y formato.', 'pptx', NULL::TEXT),
    ('CORP-004', 1, 5, 'Errores frecuentes y validación.', 'docx', NULL::TEXT),
    ('CORP-004', 1, 6, 'Actividad práctica: IA aplicada al trabajo y prompting', 'actividad', 'Laboratorio de prompts para tareas reales. Transformación de prompts básicos en prompts profesionales. Producto del módulo: Biblioteca personal de prompts aplicables al puesto.'),
    ('CORP-004', 2, 1, 'Correos y comunicaciones.', 'docx', NULL::TEXT),
    ('CORP-004', 2, 2, 'Informes y resúmenes.', 'docx', NULL::TEXT),
    ('CORP-004', 2, 3, 'Presentaciones e ideas.', 'pptx', NULL::TEXT),
    ('CORP-004', 2, 4, 'Análisis y organización de información.', 'docx', NULL::TEXT),
    ('CORP-004', 2, 5, 'Creación de plantillas y asistentes.', 'docx', NULL::TEXT),
    ('CORP-004', 2, 6, 'Actividad práctica: IA para productividad y generación de contenidos', 'actividad', 'Resolución de tareas reales del puesto con IA. Comparación entre trabajo manual y trabajo asistido. Producto del módulo: Kit de productividad con IA.'),
    ('CORP-004', 3, 1, 'Automatización conceptual de tareas.', 'pptx', NULL::TEXT),
    ('CORP-004', 3, 2, 'Flujos de trabajo con IA.', 'pptx', NULL::TEXT),
    ('CORP-004', 3, 3, 'Análisis de información y apoyo a decisiones.', 'docx', NULL::TEXT),
    ('CORP-004', 3, 4, 'Validación de resultados.', 'docx', NULL::TEXT),
    ('CORP-004', 3, 5, 'Privacidad y uso responsable.', 'docx', NULL::TEXT),
    ('CORP-004', 3, 6, 'Diseño de un caso aplicado.', 'docx', NULL::TEXT),
    ('CORP-004', 3, 7, 'Actividad práctica: IA para procesos y toma de decisiones', 'actividad', 'Diseño de un flujo de trabajo con IA. Presentación y retroalimentación del caso. Producto del módulo: Flujo de trabajo con IA aplicable al puesto.'),
    ('CORP-005', 1, 1, 'Servicio vs. experiencia del cliente.', 'pdf', NULL::TEXT),
    ('CORP-005', 1, 2, 'Expectativas y percepción.', 'pdf', NULL::TEXT),
    ('CORP-005', 1, 3, 'Momentos de verdad.', 'pdf', NULL::TEXT),
    ('CORP-005', 1, 4, 'Customer Journey.', 'docx', NULL::TEXT),
    ('CORP-005', 1, 5, 'Puntos de dolor.', 'pdf', NULL::TEXT),
    ('CORP-005', 1, 6, 'Impacto del colaborador en la experiencia.', 'pdf', NULL::TEXT),
    ('CORP-005', 1, 7, 'Actividad práctica: Customer Experience: el cliente en el centro', 'actividad', 'Construcción del recorrido de un cliente. Identificación de emociones y puntos críticos. Producto del módulo: Mapa de experiencia del cliente.'),
    ('CORP-005', 2, 1, 'Escucha activa.', 'docx', NULL::TEXT),
    ('CORP-005', 2, 2, 'Comunicación verbal y no verbal.', 'pdf', NULL::TEXT),
    ('CORP-005', 2, 3, 'Empatía.', 'pdf', NULL::TEXT),
    ('CORP-005', 2, 4, 'Preguntas poderosas.', 'pdf', NULL::TEXT),
    ('CORP-005', 2, 5, 'Lenguaje positivo.', 'pptx', NULL::TEXT),
    ('CORP-005', 2, 6, 'Comunicación bajo presión.', 'pdf', NULL::TEXT),
    ('CORP-005', 2, 7, 'Actividad práctica: Comunicación que conecta', 'actividad', 'Role play de situaciones de atención. Retroalimentación sobre lenguaje y respuesta. Producto del módulo: Guía personal de comunicación efectiva.'),
    ('CORP-005', 3, 1, 'Causas de reclamos.', 'pdf', NULL::TEXT),
    ('CORP-005', 3, 2, 'Tipología de clientes difíciles.', 'pdf', NULL::TEXT),
    ('CORP-005', 3, 3, 'Desescalamiento de conflictos.', 'pdf', NULL::TEXT),
    ('CORP-005', 3, 4, 'Qué decir y qué evitar.', 'pptx', NULL::TEXT),
    ('CORP-005', 3, 5, 'Recuperación del servicio.', 'pdf', NULL::TEXT),
    ('CORP-005', 3, 6, 'Cierre y fidelización.', 'pdf', NULL::TEXT),
    ('CORP-005', 3, 7, 'Actividad práctica: Clientes difíciles, reclamos y recuperación del servicio', 'actividad', 'Simulación de cliente agresivo, frustrado, indeciso y reclamante. Reto: escuchar → contener → comprender → responder → solucionar → cerrar. Producto del módulo: Protocolo personal para manejo de clientes difíciles.')
) AS datos(codigo_curso, numero_modulo, orden, titulo, tipo, descripcion)
JOIN public.cursos c ON c.codigo = datos.codigo_curso
JOIN public.modulos_curso mc
    ON mc.curso_id = c.id
    AND mc.numero = datos.numero_modulo
    AND mc.activo = TRUE
ON CONFLICT (modulo_id, orden) DO NOTHING;

COMMIT;

SELECT c.codigo, COUNT(DISTINCT mc.id) AS modulos,
       COUNT(cc.id) AS contenidos
FROM public.cursos c
JOIN public.modulos_curso mc ON mc.curso_id = c.id
LEFT JOIN public.contenidos_curso cc ON cc.modulo_id = mc.id
WHERE c.codigo IN (
    'ESP-001', 'ESP-002', 'ESP-003', 'ESP-004', 'ESP-005', 'ESP-006',
    'CORP-001', 'CORP-002', 'CORP-003', 'CORP-004', 'CORP-005'
)
GROUP BY c.id, c.codigo
ORDER BY c.id;

BEGIN;

UPDATE contenidos_curso AS cc
SET ruta_archivo =
    'Contenidos Mod 1 - Especialización en Contabilidad Práctica para la Gestión de MYPES/'
    || archivos.nombre
FROM (
    VALUES
        (24, '01-factura-boleta-y-notas.pptx'),
        (25, '02-datos-y-condiciones.pptx'),
        (26, '03-operaciones-y-tratamiento-tributario.pptx'),
        (27, '04-emision-anulacion-y-correccion.pdf'),
        (28, '05-errores-y-buenas-practicas.pdf')
) AS archivos(id, nombre),
modulos_curso AS mc,
cursos AS c
WHERE cc.id = archivos.id
  AND mc.id = cc.modulo_id
  AND c.id = mc.curso_id
  AND c.codigo = 'ESP-002'
  AND mc.numero = 1
RETURNING cc.id, cc.titulo, cc.tipo, cc.ruta_archivo;

COMMIT;